### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by hellodword** [Zackptg5/Curl-for-Android-Build-Script#1]
Thanks for your work!

I installed `Curl for Android` 7.65.0 on my Nexus 5 (6.0.1) with the latest Magisk (19.3).

But I can not use curl to make https request.

Always get `curl: (60) SSL certificate problem: unable to get local issuer certificate` error.

```
root@hammerhead:/sdcard # curl --version
curl 7.65.0 (arm-unknown-linux-android) libcurl/7.65.0 OpenSSL/1.1.1b zlib/1.2.11
Release-Date: 2019-05-22
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets


root@hammerhead:/sdcard # curl -I github.com/favicon.ico
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://github.com/favicon.ico

root@hammerhead:/sdcard # curl -I https://raw.githubusercontent.com/jakev/android-binaries/master/unzip
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by Zackptg5** [comment]
I haven't had the time to look into much of anything lately but this is definitely on the list.y suspicion is that I didn't like openssl properly or that I'm missing something else.
You can use the -k flag for now though

**Comment by hellodword** [comment]
OK, i will use the `-k`.
Thanks

**Comment by Zackptg5** [comment]
I'm going to keep this open until this is solved

**Comment by Zackptg5** [comment]
@hellodword Finally got this stuff figured out. Found another guy who figured it out so I forked his script and am still working on it now but I'll be closing out this repo. New repo is here: https://github.com/Zackptg5/openssl-curl-android

I'll have new builds pushed out once I get everything the way I like it
